# Clase pandas

In [8]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.4.6
3.0.3

In [9]:
capacity = pd.Series([20, 15, 25, 30], index=["Xativa", "Colon", "Ruzafa", "Angel Gimera"])
print(capacity)

Xativa          20
Colon           15
Ruzafa          25
Angel Gimera    30
dtype: int64

In [10]:
print(capacity * 0.5)

Xativa          10.0
Colon            7.5
Ruzafa          12.5
Angel Gimera    15.0
dtype: float64

In [11]:
mini = pd.DataFrame({
    "Station": ["Xativa", "Colon", "Ruzafa", "Angel Gimera"],
    "Capacity": [20, 15, 25, 30],
    "Bikes": [12, 3, 18, 25]
})

print(mini)

        Station  Capacity  Bikes
0        Xativa        20     12
1         Colon        15      3
2        Ruzafa        25     18
3  Angel Gimera        30     25

In [12]:
print(mini.columns.to_list())
print(mini.dtypes)

['Station', 'Capacity', 'Bikes']
Station       str
Capacity    int64
Bikes       int64
dtype: object

In [14]:
mini["Ocupancy"] = (mini["Bikes"] / mini["Capacity"]).round(2)

mini["Status"] = np.where(mini["Ocupancy"] > 0.7, "High", "Okay")

print(mini)

        Station  Capacity  Bikes  Ocupancy Status
0        Xativa        20     12      0.60   Okay
1         Colon        15      3      0.20   Okay
2        Ruzafa        25     18      0.72   High
3  Angel Gimera        30     25      0.83   High

In [24]:
stations = pd.read_csv("./data/stations.csv")

stations.head()

,station_id,name,district,lat,lon,capacity,opened
0,1,"Calle Caballeros, 22",Ciutat Vella,39.475962,-0.383585,15.0,2014-01-07
1,2,"Calle San Vicente Mártir, 43",Ciutat Vella,39.473832,-0.377248,30.0,2012-03-02
2,3,"Calle Caballeros, 78",Ciutat Vella,39.474096,-0.373120,30.0,2019-04-14
3,4,"Plaza de la Reina, 76",Ciutat Vella,39.474658,-0.375356,25.0,2018-05-20
4,5,"Calle San Vicente Mártir, 54",Ciutat Vella,39.477193,-0.376522,20.0,2012-08-21

In [21]:
usage_hourly = pd.read_csv("./data/usage_hourly.csv")

usage_hourly.head()

   station_id            timestamp  rentals  returns  bikes_available
0          58  2026-09-25 22:00:00        0        0             20.0
1          24  2026-09-13 02:00:00        0        0             16.0
2          17  2026-09-04 03:00:00        0        0             15.0
3          36  2026-09-13 03:00:00        0        0             14.0
4          39  2026-09-20 11:00:00        0        4             18.0

In [27]:
stations.describe()

       station_id        lat        lon   capacity
count   60.000000  60.000000  60.000000  58.000000
mean    30.500000  39.470015  -0.370467  23.448276
std     17.464249   0.010947   0.020668   6.435026
min      1.000000  39.446556  -0.411840  15.000000
25%     15.750000  39.463084  -0.388257  20.000000
50%     30.500000  39.468368  -0.372618  25.000000
75%     45.250000  39.476270  -0.356271  25.000000
max     60.000000  39.491789  -0.329369  35.000000

In [28]:
usage_hourly.describe()

         station_id       rentals       returns  bikes_available
count  43350.000000  43350.000000  43350.000000     42480.000000
mean      30.497416      1.885329      1.687843        12.050235
std       17.319319     16.740842      2.667507         6.983225
min        1.000000      0.000000     -1.000000         0.000000
25%       15.000000      0.000000      0.000000         8.000000
50%       30.000000      1.000000      1.000000        12.000000
75%       45.000000      2.000000      2.000000        16.000000
max       60.000000    999.000000     29.000000        35.000000

In [35]:
print(stations.isna())
print(f"El total de duplicados es: {stations.duplicated().sum()}")
print(stations.nunique())
print(stations.value_counts())

    station_id   name  district    lat    lon  capacity  opened
0        False  False     False  False  False     False   False
1        False  False     False  False  False     False   False
2        False  False     False  False  False     False   False
3        False  False     False  False  False     False   False
4        False  False     False  False  False     False   False
5        False  False     False  False  False     False   False
6        False  False     False  False  False     False   False
7        False  False     False  False  False     False   False
8        False  False     False  False  False     False   False
9        False  False     False  False  False     False   False
10       False  False     False  False  False     False   False
11       False  False     False  False  False     False   False
12       False  False     False  False  False     False   False
13       False  False     False  False  False      True   False
14       False  False     False  False  False     False   False
15       False  False     False  False  False     False   False
16       False  False     False  False  False     False   False
17       False  False     False  False  False     False   False
18       False  False     False  False  False     False   False
19       False  False     False  False  False     False   False
20       False  False     False  False  False     False   False
21       False  False     False  False  False     False   False
22       False  False     False  False  False     False   False
23       False  False     False  False  False     False   False
24       False  False     False  False  False     False   False
25       False  False     False  False  False     False   False
26       False  False     False  False  False     False   False
27       False  False     False  False  False     False   False
28       False  False     False  False  False     False   False
29       False  False     False  False  False     False   False
30       False  False     False  False  False     False   False
31       False  False     False  False  False     False   False
32       False  False     False  False  False     False   False
33       False  False     False  False  False     False   False
34       False  False     False  False  False     False   False
35       False  False     False  False  False     False   False
36       False  False     False  False  False     False   False
37       False  False     False  False  False     False   False
38       False  False     False  False  False     False   False
39       False  False     False  False  False     False   False
40       False  False     False  False  False     False   False
41       False  False     False  False  False     False   False
42       False  False     False  False  False     False   False
43       False  False     False  False  False     False   False
44       False  False     False  False  False     False   False
45       False  False     False  False  False     False   False
46       False  False     False  False  False     False   False
47       False  False     False  False  False     False   False
48       False  False     False  False  False     False   False
49       False  False     False  False  False     False   False
50       False  False     False  False  False     False   False
51       False  False     False  False  False     False   False
52       False  False     False  False  False     False   False
53       False  False     False  False  False     False   False
54       False  False     False  False  False      True   False
55       False  False     False  False  False     False   False
56       False  False     False  False  False     False   False
57       False  False     False  False  False     False   False
58       False  False     False  False  False     False   False
59       False  False     False  False  False     False   False
El total de duplicados es: 0
station_id    60
name          60
district      19
lat           60
lon           60
capacity       5
opened        59
dtype: int64
station_id  name                              district           lat        lon        capacity  opened
1           Calle Caballeros, 22              Ciutat Vella       39.475962  -0.383585  15.0      2014-01-07    1
2           Calle San Vicente Mártir, 43      Ciutat Vella       39.473832  -0.377248  30.0      2012-03-02    1
3           Calle Caballeros, 78              Ciutat Vella       39.474096  -0.373120  30.0      2019-04-14    1
4           Plaza de la Reina, 76             Ciutat Vella       39.474658  -0.375356  25.0      2018-05-20    1
5           Calle San Vicente Mártir, 54      Ciutat Vella       39.477193  -0.376522  20.0      2012-08-21    1
6           Calle Caballeros, 63              Ciutat Vella       39.477626  -0.376929  30.0      2010-08-04    1
7           Calle de la Paz, 54               CIUTAT VELLA       39.482298  -0.378853  25.0      2016-03-03    1
8           Plaza de la Reina, 52             Ciutat Vella       39.475700  -0.380678  35.0      2018-11-07    1
9           Calle Ruzafa, 95                  Eixample           39.470406  -0.368664  25.0      2019-07-17    1
10          Calle Sueca, 68                   Eixample           39.467738  -0.374076  15.0      2013-07-12    1
11          Calle Cuba, 83                    Eixample           39.468507  -0.371182  15.0      2017-03-08    1
12          Calle Cuba, 28                    Eixample           39.470777  -0.369624  25.0      2012-04-12    1
13          Calle Colón, 88                   Eixample           39.461737  -0.361762  15.0      2014-01-13    1
15          Calle Erudito Orellana, 69        Extramurs          39.468229  -0.388087  15.0      2018-01-29    1
16          Calle Erudito Orellana, 62        Extramurs          39.475152  -0.390222  25.0      2019-12-15    1
17          Avenida Pérez Galdós, 7           Extramurs          39.466127  -0.393724  30.0      2013-06-24    1
18          Avenida Pérez Galdós, 68          Extramurs          39.467627  -0.386972  25.0      2019-08-27    1
19          Calle Erudito Orellana, 106       Extramurs          39.463037  -0.390795  15.0      2019-07-18    1
20          Avenida Campanar, 3               Campanar           39.489480  -0.393180  15.0      2016-11-27    1
21          Avenida Campanar, 58              Campanar           39.490148  -0.395710  30.0      2016-04-05    1
22          Calle Valle de la Ballestera, 59  Campanar           39.485229  -0.393138  20.0      2012-04-09    1
23          Avenida Campanar, 113             Campanar           39.482344  -0.395784  15.0      2016-10-15    1
24          Avenida Burjassot, 65             La Saïdia          39.490352  -0.379828  30.0      2016-03-18    1
25          Avenida Primado Reig, 97          La Saïdia          39.488469  -0.363867  15.0      2014-04-30    1
26          Avenida Burjassot, 92             La Saïdia          39.483748  -0.376187  25.0      2018-09-06    1
27          Calle Sagunto, 75                 La Saïdia          39.491789  -0.373427  25.0      2013-09-16    1
28          Avenida Primado Reig, 80          La Saïdia          39.487854  -0.369931  20.0      2010-10-13    1
29          Paseo de la Alameda, 10           El Pla del Real    39.474792  -0.369152  35.0      2015-06-01    1
30          Avenida Aragón, 79                El Pla del Real    39.477891  -0.353343  30.0      2013-07-10    1
31          Avenida Aragón, 38                 El Pla del Real   39.481783  -0.358157  20.0      2018-04-28    1
32          Paseo de la Alameda, 57           El Pla del Real    39.475274  -0.355844  35.0      2017-03-02    1
33          Calle Jaime Roig, 89              El Pla del Real    39.478849  -0.353506  25.0      2016-09-12    1
34          Calle Músico Ayllón, 86           L'Olivereta        39.460852  -0.406406  25.0      2017-01-25    1
35          Calle Archiduque Carlos, 72       L'Olivereta        39.467191  -0.393574  15.0      2013-11-07    1
36          Calle Archiduque Carlos, 115      L'Olivereta        39.465034  -0.411840  25.0      2013-12-28    1
37          Avenida Tres Forques, 13          Patraix            39.459364  -0.395132  20.0      2013-07-10    1
38          Calle Sevilla, 70                 Patraix            39.465197  -0.393794  20.0      2011-09-10    1
39          Calle Sevilla, 94                 Patraix            39.454616  -0.396956  25.0      2017-09-25    1
40          Avenida Real de Madrid, 66        Jesús              39.456397  -0.390706  25.0      2017-12-15    1
41          Calle San Vicente Mártir, 44      Jesús              39.454987  -0.382030  25.0      2010-10-05    1
42          Calle Jesús, 15                   Jesús              39.456759  -0.388768  20.0      2013-09-05    1
43          Avenida Ausiàs March, 68          Quatre Carreres    39.453155  -0.362027  25.0      2011-03-06    1
44          Calle Escultor José Capuz, 102    Quatre Carreres    39.451418  -0.362716  35.0      2013-04-23    1
45          Avenida Ausiàs March, 86          Quatre Carreres    39.446556  -0.372117  15.0      2019-11-09    1
46          Avenida Hermanos Maristas, 33     Quatre Carreres    39.450173  -0.357309  25.0      2011-03-26    1
47          Avenida Peris y Valero, 79        Quatre Carreres    39.454280  -0.367910  35.0      2015-09-26    1
48          Paseo Marítimo, 55                Poblats Marítims   39.468022  -0.330817  15.0      2015-04-01    1
49          Calle Reina, 108                  Poblats Marítims   39.465897  -0.331469  35.0      2013-11-18    1
50          Avenida del Puerto, 93            Poblats Marítims   39.465460  -0.331478  35.0      2017-08-08    1
51          Calle Reina, 92                   Poblats Marítims   39.465816  -0.335934  20.0      2012-07-02    1
52          Avenida del Puerto, 107           Poblats Marítims   39.465304  -0.329445  20.0      2012-12-26    1
53          Calle Menorca, 50                 Poblats Marítims   39.465144  -0.329369  20.0      2019-04-11    1
54          Avenida de Francia, 70            Camins al Grau     39.462941  -0.348854  25.0      2015-03-12    1
56          Avenida de Francia, 69            Camins al Grau     39.465249  -0.351741  15.0      2012-05-31    1
57          Calle Doctor Manuel Candela, 103  Camins al Grau     39.458795  -0.356413  25.0      2014-01-01    1
58          Calle Ramón Llull, 36             ALGIRÓS            39.472760  -0.347165  20.0      2014-08-22    1
59          Calle Ramón Llull, 93             Algirós            39.472084  -0.347888  20.0      2015-02-12    1
60          Calle Ramón Llull, 17             algirós            39.474144  -0.338508  20.0      2011-03-15    1
Name: count, dtype: int64

In [32]:
weather = pd.read_json("./data/weather_daily.json")
weather.head()

        date  temp_max  temp_min  rain_mm  wind_kmh condition
0 2026-09-01      31.6      24.2      0.0      29.4     sunny
1 2026-09-02      28.5      20.5      0.0      24.6     sunny
2 2026-09-03      27.8      21.0      0.0       5.4    cloudy
3 2026-09-04      27.3      21.1      0.0      30.0    cloudy
4 2026-09-05      29.0      21.3      0.0       5.3     sunny

In [39]:
print(stations.loc[5, "name"])

print("\n")

print(stations.iloc[0, :3])

Calle Caballeros, 63


station_id                       1
name          Calle Caballeros, 22
district              Ciutat Vella
Name: 0, dtype: object

In [42]:
stations.query("capacity > 25").sort_values("station_id", ascending=True)

,station_id,name,district,lat,lon,capacity,opened
1,2,"Calle San Vicente Mártir, 43",Ciutat Vella,39.473832,-0.377248,30.0,2012-03-02
2,3,"Calle Caballeros, 78",Ciutat Vella,39.474096,-0.373120,30.0,2019-04-14
5,6,"Calle Caballeros, 63",Ciutat Vella,39.477626,-0.376929,30.0,2010-08-04
7,8,"Plaza de la Reina, 52",Ciutat Vella,39.475700,-0.380678,35.0,2018-11-07
16,17,"Avenida Pérez Galdós, 7",Extramurs,39.466127,-0.393724,30.0,2013-06-24
20,21,"Avenida Campanar, 58",Campanar,39.490148,-0.395710,30.0,2016-04-05
23,24,"Avenida Burjassot, 65",La Saïdia,39.490352,-0.379828,30.0,2016-03-18
28,29,"Paseo de la Alameda, 10",El Pla del Real,39.474792,-0.369152,35.0,2015-06-01
29,30,"Avenida Aragón, 79",El Pla del Real,39.477891,-0.353343,30.0,2013-07-10
31,32,"Paseo de la Alameda, 57",El Pla del Real,39.475274,-0.355844,35.0,2017-03-02
43,44,"Calle Escultor José Capuz, 102",Quatre Carreres,39.451418,-0.362716,35.0,2013-04-23
46,47,"Avenida Peris y Valero, 79",Quatre Carreres,39.454280,-0.367910,35.0,2015-09-26
48,49,"Calle Reina, 108",Poblats Marítims,39.465897,-0.331469,35.0,2013-11-18
49,50,"Avenida del Puerto, 93",Poblats Marítims,39.465460,-0.331478,35.0,2017-08-08

In [43]:
stations[stations["name"].str.contains("Avenida")]

,station_id,name,district,lat,lon,capacity,opened
16,17,"Avenida Pérez Galdós, 7",Extramurs,39.466127,-0.393724,30.0,2013-06-24
17,18,"Avenida Pérez Galdós, 68",Extramurs,39.467627,-0.386972,25.0,2019-08-27
19,20,"Avenida Campanar, 3",Campanar,39.489480,-0.393180,15.0,2016-11-27
20,21,"Avenida Campanar, 58",Campanar,39.490148,-0.395710,30.0,2016-04-05
22,23,"Avenida Campanar, 113",Campanar,39.482344,-0.395784,15.0,2016-10-15
23,24,"Avenida Burjassot, 65",La Saïdia,39.490352,-0.379828,30.0,2016-03-18
24,25,"Avenida Primado Reig, 97",La Saïdia,39.488469,-0.363867,15.0,2014-04-30
25,26,"Avenida Burjassot, 92",La Saïdia,39.483748,-0.376187,25.0,2018-09-06
27,28,"Avenida Primado Reig, 80",La Saïdia,39.487854,-0.369931,20.0,2010-10-13
29,30,"Avenida Aragón, 79",El Pla del Real,39.477891,-0.353343,30.0,2013-07-10
30,31,"Avenida Aragón, 38",El Pla del Real,39.481783,-0.358157,20.0,2018-04-28
36,37,"Avenida Tres Forques, 13",Patraix,39.459364,-0.395132,20.0,2013-07-10
39,40,"Avenida Real de Madrid, 66",Jesús,39.456397,-0.390706,25.0,2017-12-15
42,43,"Avenida Ausiàs March, 68",Quatre Carreres,39.453155,-0.362027,25.0,2011-03-06
44,45,"Avenida Ausiàs March, 86",Quatre Carreres,39.446556,-0.372117,15.0,2019-11-09
45,46,"Avenida Hermanos Maristas, 33",Quatre Carreres,39.450173,-0.357309,25.0,2011-03-26
46,47,"Avenida Peris y Valero, 79",Quatre Carreres,39.454280,-0.367910,35.0,2015-09-26
49,50,"Avenida del Puerto, 93",Poblats Marítims,39.465460,-0.331478,35.0,2017-08-08
51,52,"Avenida del Puerto, 107",Poblats Marítims,39.465304,-0.329445,20.0,2012-12-26
53,54,"Avenida de Francia, 70",Camins al Grau,39.462941,-0.348854,25.0,2015-03-12
54,55,"Avenida del Puerto, 76",Camins al Grau,39.463100,-0.350523,NaN,2013-06-12
55,56,"Avenida de Francia, 69",Camins al Grau,39.465249,-0.351741,15.0,2012-05-31

In [44]:
print(stations.columns)
print(usage_hourly.columns)

Index(['station_id', 'name', 'district', 'lat', 'lon', 'capacity', 'opened'], dtype='str')
Index(['station_id', 'timestamp', 'rentals', 'returns', 'bikes_available'], dtype='str')

In [ ]:
#reto 4

n_999 = (usage_hourly["rentals"] == 999).sum()
n_neg = (usage_hourly["returns"] < 0).sum()

print(f"Filas con 999 alquileres: {n_999}")
print(f"Filas con devoluciones negativas: {n_neg}")

Filas con 999 alquileres: 12
Filas con devoluciones negativas: 8

In [ ]:
# reto 5

grandes = stations.loc[
    (stations["district"] == "Ciutat Vella") & (stations["capacity"] >= 30),
    "station_id"
].sort_values().tolist()

print(grandes)

[2, 3, 6, 8]

In [69]:
# reto 6

validas = usage_hourly[
    (usage_hourly["rentals"] != 999) & (usage_hourly["returns"] >= 0)
]

ranking = validas.sort_values(
    by=["returns", "timestamp", "station_id"],
    ascending=[False, True, True],
)

print(ranking.head(3))
print(ranking.iloc[0])

       station_id            timestamp  rentals  returns  bikes_available
18016          60  2026-09-02 08:00:00        6       29             20.0
33904          12  2026-09-10 09:00:00       10       29             25.0
25798          31  2026-09-09 09:00:00       12       26             20.0
station_id                          60
timestamp          2026-09-02 08:00:00
rentals                              6
returns                             29
bikes_available                   20.0
Name: 18016, dtype: object

In [73]:
# reto 7

clean = usage_hourly.copy()
n_inicial = len(clean)

clean = clean.drop_duplicates()
n_duplicados = n_inicial - len(clean)

n_antes = len(clean)
clean = clean[
    clean["rentals"].between(0, 100) & clean["returns"].between(0, 100)
]
n_imposibles = n_antes - len(clean)

print(f"Filas iniciales: {n_inicial}")
print(f"Duplicados quitados: {n_duplicados}")
print(f"Imposibles quitados: {n_imposibles}")
print(f"Total quitado: {n_inicial - len(clean)}")
print(f"Filas finales: {len(clean)}")

Filas iniciales: 43350
Duplicados quitados: 150
Imposibles quitados: 20
Total quitado: 170
Filas finales: 43180

In [74]:
# reto 8
clean["timestamp"] = pd.to_datetime(clean["timestamp"])

clean["date"] = clean["timestamp"].dt.date
clean["hour"] = clean["timestamp"].dt.hour
clean["weekday"] = clean["timestamp"].dt.day_name()
clean["is_weekend"] = clean["timestamp"].dt.dayofweek >= 5

print(clean[["timestamp", "date", "hour", "weekday", "is_weekend"]].head())
print(clean.dtypes)

            timestamp        date  hour weekday  is_weekend
0 2026-09-25 22:00:00  2026-09-25    22  Friday       False
1 2026-09-13 02:00:00  2026-09-13     2  Sunday        True
2 2026-09-04 03:00:00  2026-09-04     3  Friday       False
3 2026-09-13 03:00:00  2026-09-13     3  Sunday        True
4 2026-09-20 11:00:00  2026-09-20    11  Sunday        True
station_id                  int64
timestamp          datetime64[us]
rentals                     int64
returns                     int64
bikes_available           float64
date                       object
hour                        int32
weekday                       str
is_weekend                   bool
dtype: object